modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-TheAether/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Aether.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-the-aether-legacy"
logoFile="logo.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="dynamictrees"
    type="required"
    versionRange="${dynamic_trees_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="dynamictreesplus"
    type="optional"
    versionRange="${dynamic_trees_plus_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="aether"
    type="required"
    versionRange="${aether_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="deep_aether"
    type="optional"
    versionRange="${deep_aether_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="gravitation"
    type="optional"
    versionRange="${gravitation_version_range}"
    ordering="AFTER"
    side="BOTH"
